apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/muthuri-dev/devops-eks-helm-terraform-ansible.git
    targetRevision: dev
    path: helm/golang-app
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: VAULT_ADDR
          value: "http://a7f90ff1105d746a5a785087b130fc75-232304810.us-east-1.elb.amazonaws.com:8200"
        - name: AVP_TYPE
          value: "vault"
        - name: AVP_AUTH_TYPE
          value: "k8s"
        - name: AVP_K8S_ROLE
          value: "golang-app"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
