# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: golang-app-secrets
  namespace: default
  labels:
    app: golang-app
type: Opaque
stringData:
  # Database Configuration
  DB_HOST: "postgresql-db-rw.databases.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "app"
  DB_PASSWORD: "CxOy2AAXoFfmsq8Vxx7j6BC50enr7bBGxVNPmojiKqNpEx2AenDjXtDoG3Ow5YKv"
  DB_NAME: "golang_app"
  DB_SSL_MODE: "disable"

  # Server Configuration
  PORT: "8080"
