# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: golang-app-secrets
  namespace: default
  labels:
    app: golang-app
type: Opaque
data:
  # Database Configuration
  DB_HOST: cG9zdGdyZXNxbC1kYi1ydy5kYXRhYmFzZXMuc3ZjLmNsdXN0ZXIubG9jYWw= # postgresql-db-rw.databases.svc.cluster.local
  DB_PORT: NTQzMg== # 5432
  DB_USER: YXBw # app
  DB_PASSWORD: Q3hPeTJBQVhvRmZtc3E4Vnh4N2o2QkM1MGVucjdiQkd4Vk5QbW9qaUtxTnBFeDJBRW5Ealh0RG9HM09XNVlLdg==
  DB_NAME: Z29sYW5nX2FwcA== # golang_app
  DB_SSL_MODE: ZGlzYWJsZQ== # disable

  # Server Configuration
  PORT: ODA4MA== # 8080
