# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: golang-app-secrets
  namespace: default
  labels:
    app: golang-app
type: Opaque
data:
  # Database Configuration
  DB_HOST: YWQ2MGYwNGExY2I4NTQwNDJiMzRjY2JmYzlmZDUwMTctMTI0NTQxNzc1MC51cy1lYXN0LTEuZWxiLmFtYXpvbmF3cy5jb20=
  DB_PORT: NTQzMg==
  DB_USER: YXBw
  DB_PASSWORD: Q3hPeTJBQVhvRmZtc3E4Vnh4N2o2QkM1MGVucjdiQkd4Vk5QbW9qaUtxTnBFeDJBRW5Ealh0RG9HM09XNVlLdg==
  DB_NAME: Z29sYW5nX2FwcA==
  DB_SSL_MODE: ZGlzYWJsZQ==

  # Server Configuration
  PORT: ODA4MA== # 8080
