name: Build and Deploy Events API

on:
    push:
        branches:
            - main
        paths:
            - "application/**"

env:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: golang-app
    IMAGE_NAME: golang-app

jobs:
    build-and-publish:
        permissions:
            id-token: write
            contents: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Get AWS credentials from Vault
              uses: hashicorp/vault-action@v3
              with:
                  url: ${{ secrets.VAULT_URL }}
                  token: ${{ secrets.VAULT_TOKEN }}
                  tlsSkipVerify: true
                  secrets: |
                      kv/data/github_workflows aws_access_key_id | AWS_ACCESS_KEY_ID ;
                      kv/data/github_workflows aws_secret_access_key | AWS_SECRET_ACCESS_KEY

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Determine image tag
              id: determine-tag
              run: |
                  TAG=$(git rev-parse --short HEAD)
                  echo "TAG=$TAG" >> $GITHUB_OUTPUT
                  echo "VERSION=$TAG" >> $GITHUB_OUTPUT

            - name: Build Docker image
              run: |
                  TAG=${{ steps.determine-tag.outputs.TAG }}
                  REPOSITORY="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}"

                  cd application
                  docker build \
                    --build-arg VERSION=${{ steps.determine-tag.outputs.VERSION }} \
                    -t $REPOSITORY:$TAG \
                    -t $REPOSITORY:latest \
                    .

            - name: Push Docker image
              run: |
                  TAG=${{ steps.determine-tag.outputs.TAG }}
                  REPOSITORY="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}"

                  docker push $REPOSITORY:$TAG
                  docker push $REPOSITORY:latest

            - name: Output Image name
              run: |
                  echo "Image pushed to ECR: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.determine-tag.outputs.TAG }}"

    update-helm-chart:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        needs: build-and-publish
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Get AWS credentials from Vault
              uses: hashicorp/vault-action@v3
              with:
                  url: ${{ secrets.VAULT_URL }}
                  token: ${{ secrets.VAULT_TOKEN }}
                  tlsSkipVerify: true
                  secrets: |
                      kv/data/github_workflows aws_access_key_id | AWS_ACCESS_KEY_ID ;
                      kv/data/github_workflows aws_secret_access_key | AWS_SECRET_ACCESS_KEY

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Get image tag
              id: get-tag
              run: |
                  TAG=$(git rev-parse --short HEAD)
                  echo "TAG=$TAG" >> $GITHUB_OUTPUT

            - name: Setup Git Config
              uses: fregante/setup-git-user@v2

            - name: Update image in helm values.yaml
              run: |
                  TAG=${{ steps.get-tag.outputs.TAG }}
                  REPOSITORY="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}"

                  echo "Updating image repository and tag in helm/golang-app/values.yaml"
                  sed -i "s|repository: .*|repository: $REPOSITORY|" helm/golang-app/values.yaml
                  sed -i "s|tag: .*|tag: \"$TAG\"|" helm/golang-app/values.yaml

            - name: Commit & push changes
              run: |
                  git add helm/golang-app/values.yaml
                  if ! git diff --cached --quiet; then
                    git commit -m "ci: update ${{ env.IMAGE_NAME }} image to ${{ steps.get-tag.outputs.TAG }}"
                    git push origin main
                  else
                    echo "No changes to commit."
                  fi
